- hosts: all
  gather_facts: true
  vars:
    # ssh stuff
    ansible_become: yes
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

  pre_tasks:
    - name: import repositories
      ansible.builtin.set_fact:
        nexusRepos: "{{ lookup('file','vars/nexus_repos.json') | from_json }}"

  tasks:
    - name: load globals
      ansible.builtin.import_role:
        name: sem_globals

    - name: present nexus repositories
      ansible.builtin.import_role:
        name: ansible-nexus-repositories
    
    - name: dockerhub - pull images
      ansible.builtin.import_tasks: tasks/dockerhub.yml
