- name: Load container list
  ansible.builtin.set_fact:
    containers: "{{ lookup('file','files/containers.json') }}"

- name: Caching container images
  command: "docker pull {{ nexusIP }}:{{item.0.registry.proxyport}}/{{ item.1 }}"
   # msg: "Registry: {{ item.0.registry.name }}, Image: {{ item.1 }}"
  with_subelements:
    - "{{ containers }}"
    - images
  loop_control:
    label: "Image: {{ item.1 }} via proxy from {{ item.0.registry.name }} "