- name: load image list
  ansible.builtin.set_fact:
    json_content: "{{ lookup('file','vars/containers.dockerhub.json') | from_json }}"

- name: Extract registry and image names
  debug:
    msg: "{{ item.registry }}/ {{ image.image }}"
  loop: "{{ json_content }}"
  loop_control:
    loop_var: item
  with_items: "{{ item.images }}"
