- name: load image list
  ansible.builtin.set_fact:
    json_content: "{{ lookup('file','vars/containers.dockerhub.json') }}"

- name: Extract registry and image names
  debug:
    msg: "{{ item.registry }} \n {{ item.images }}"
  loop: "{{ json_content }}"
  loop_control:
    loop_var: item
