- name: load image list
  ansible.builtin.set_fact:
    images: "{{ lookup('file','vars/containers.dockerhub.json') | from_json }}"

- name: Extract registry and image names
  debug:
    msg: "{{ item.registry }}/ {{ item.image }}"
  loop: "{{ images }}"
  loop_control:
    loop_var: item
  with_items:
    - "{{ item.images }}"
  register: result
  
- name: Output concatenated registry and image names
  debug:
    msg: "{{ item.item.registry }}/ {{ item.item.image }}"
  with_items: "{{ result.results }}"