- name: load image list
  ansible.builtin.set_fact:
    images: "{{ lookup('file','vars/containers.dockerhub.json') | from_json }}"

- name: Extract registry and image names
  debug:
    msg: "{{ item.registry }}/{{ item.image }}"
  loop: "{{ images | json_query('[].{registry: registry, image: images[*].image}') | flatten(levels=1) }}"