- name: load dockerhub image list
  ansible.builtin.set_fact:
    images: "{{ lookup('file','vars/containers.dockerhub.json') | b64decode | from_json }}"
  
- name: retrieve all registries
  set_fact:
       registries: "{{ images | dict2items }}"

- name: prepare images lists
  set_fact:
    registry_images: "{{ registry_images | default({}) | combine({item.key: item.value | json_query('[*]')}) }}"
  loop: "{{ registries }}"

- name: Display extracted subentries
  debug:
    msg: "Registry: {{ item.key }} - Image: {{ item.value }}"
  loop: "{{ registry_images | dict2items }}"