- name: load image list
  ansible.builtin.set_fact:
    images: "{{ lookup('file','vars/containers.dockerhub.json') | from_json }}"

- name: prepare images lists
  set_fact:
    registry_images: "{{ registry_images | default([]) + item | dict2items }}"
  loop: "{{ images }}"

- name: Display extracted subentries
  debug:
    msg: "Registry: {{ item.key }} - Image: {{ item.value }}"
  loop: "{{ registry_images }}"