- name: load image list
  ansible.builtin.set_fact:
    json_content: "{{ lookup('file','vars/containers.dockerhub.json') }}"

- debug:
    msg: "{{ item.registry }}"
    loop: "{{ json_content }}"

#- name: Extract registry and image names
#  debug:
#    msg: "{{ item.registry }}/ {{ item.image }}"
#  loop: "{{ json_content | flatten(levels=2) }}"
#  loop_control:
#    loop_var: item
