- name: load image list
  ansible.builtin.set_fact:
    json_content: "{{ lookup('file','vars/containers.dockerhub.json') }}"

- name: Create interfaces Dictionary
  set_fact:
    images: "{{ json_content.parsed.images }}"

- debug:
    var: images
