- name: pipy - copy requirements
  # necessary, because of permission probs in container runtimes
  copy: 
    src: files/pipy
    dest: /tmp/

- name: pipy - find all requirements
  find:
    paths: "/tmp/pipy"
    file_type: file
    recurse: yes
  register: requirements

- debug:
    var: requirements

- name: pipy - install requirements
  pip:
    requirements: "{{ item.path }}"
  loop: requirements 

